#include <stdio.h>

int main (int argc, char **argv)
//CODIGO PREGUNTAS
{
	printf("LAS MEJORES GENERCIONES DE COMPUTADORAS \n\n");
	printf("Primera generación (Década de 1940): Se caracterizó por el uso de tubos de vacío y fue el comienzo de la computación electrónica. Ejemplos notables incluyen la ENIAC y la UNIVAC I.\n \n");
	printf("3 CARACTERISTICAS DE LAS NUEVAS GENERACIONES DE COMPUTADORES \n\n");
	printf("Mayor rendimiento de procesamiento: Las nuevas generaciones de computadoras tienden a incorporar procesadores más potentes y eficientes, lo que se traduce en un mayor rendimiento de procesamiento. Esto permite ejecutar aplicaciones más complejas, realizar tareas intensivas en cómputo y mejorar la experiencia del usuario en general.\n Tecnologías de conectividad avanzadas: Cada nueva generación suele introducir mejoras en las tecnologías de conectividad, como velocidades de transferencia de datos más rápidas, Wi-Fi mejorado, soporte para redes móviles más avanzadas y puertos de alta velocidad. Esto permite una mejor comunicación entre dispositivos, acceso más rápido a la información y una conectividad más fluida en entornos digitales. \n Innovaciones en almacenamiento: Las nuevas generaciones de computadoras suelen traer consigo avances en tecnologías de almacenamiento, como unidades de estado sólido (SSD) más rápidas y capaces, así como técnicas de almacenamiento en la nube más eficientes y seguras. Estas mejoras permiten un acceso más rápido a los datos, una mayor capacidad de almacenamiento y una mejor protección de la información. \n \n");
	printf("¿CUALES SON LAS 3 CARACTERISTICAS DE LA SEGUNDA GENERACION? \n\n");
	printf ("Uso de transistores: En la segunda generación, los transistores reemplazaron los tubos de vacío utilizados en la primera generación. Los transistores eran componentes electrónicos más pequeños, más eficientes y más confiables que los tubos de vacío. Esta innovación permitió que las computadoras fueran más compactas, consumieran menos energía y generaran menos calor. Los transistores también eran más duraderos y requerían menos mantenimiento que los tubos de vacío, lo que mejoró significativamente la confiabilidad de las computadoras. \Mayor velocidad y capacidad: La introducción de transistores permitió a las computadoras de segunda generación funcionar a velocidades mucho más altas que las de la primera generación. Esto resultó en un aumento significativo en la capacidad de procesamiento y en la velocidad de ejecución de tareas. Además, las computadoras de segunda generación podían manejar un mayor número de instrucciones y datos, lo que amplió sus capacidades y aplicaciones. \n Uso de memoria magnética y cintas perforadas: En la segunda generación, se comenzaron a utilizar tecnologías de almacenamiento más avanzadas, como la memoria magnética y las cintas perforadas. La memoria magnética permitía un acceso más rápido a los datos y un almacenamiento más eficiente que las técnicas utilizadas en la primera generación. Las cintas perforadas también se usaban para almacenar y cargar programas y datos en las computadoras.\n Estas tres características marcaron una transición importante hacia computadoras más eficientes, más rápidas y más confiables durante la segunda generación. El uso de transistores en lugar de tubos de vacío allanó el camino para futuras mejoras en la tecnología informática \n 'n.");

	return 0;
	
}

